# site settings
title: 3-Tier
subtitle: Korea Autonomous Driving Development Innovation(R&D)
email: kiapisp2501@gmail.com
description: This page is the public SW repository<br /> for the "3Tier" research and development project.
baseurl: "/3Tier" # the subpath of your site, e.g. /blog
url: https://www.kiapi.or.kr/index.html # the base hostname & protocol for your site
author: Korea Intelligent Automotive Parts Promotion Institute
street_address: 201 Gukguk Industrial Complex, Guji-myeon, Dalseong-gun, Daegu
city: Daegu
state: Daegu
zip_code: 43011
country: Republic of Korea
phone: (053) 670-7800

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  GitLab:
  Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  Instagram:
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195
  Twitter: https://twitter.com/andrewbanchich
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
